### ISSUE TITLE
Certain names only resolved under the original intended source if multiple sources provided

### ISSUE THREAD

**Issue by jtmiller28** [EnquistLab/RTNRS#11]
Hello, 
I encountered an odd output where TNRS will only resolve a name if I provide it both with world of flora & tropicos as arguments, when its resolution is dependent only on wfo as listed in the Source column output. 

Example: 
```{r}
TNRS_check_s <- TNRS("psilochenia occidentalis ssp. costata", sources = "wfo", classification = "wfo", mode = "resolve", matches = "best", accuracy = NULL)

TNRS_check_m <- TNRS("psilochenia occidentalis ssp. costata", sources = c("wfo", "tropicos"), classification = "wfo", mode = "resolve", matches = "best", accuracy = NULL)

print(TNRS_check_s)
print(TNRS_check_m)
```

The output will show resolution for TNRS_check_m, but the source will specify wfo online as the resolving catalogue. The URL matched is also a valid name under WFO: http://www.worldfloraonline.org/taxon/wfo-0000067322 . 

Let me know if I can provide any more info, Thanks!

**Comment by bmaitner** [comment]
Hey @ojalaquellueva I wonder if this issue is related to https://github.com/EnquistLab/RTNRS/issues/6  ?

As @jtmiller28 helpfully notes, the issue can't simply be that the species is missing from the wfo, as when the name IS matched in the second query, it is matched to the wfo.

**Comment by ojalaquellueva** [comment]
Returning to this old issue. I cannot replicate it exactly because tropicos is not longer used by the TNRS. But wfo alone resolves the name just fine. Perhaps it was accidentally resolved by a database update?

```
$ wd="/Users/bboyle/Documents/bien/tnrs/test"
$ cat << EOT > 'names.csv'
id,species
1,"psilochenia occidentalis ssp. costata"
EOT
$ tnrsapi.sh -f "${wd}/names.csv" -s wfo
 
Names submitted:
|   id | species                               |
| ---- | ------------------------------------- |
| True | psilochenia occidentalis ssp. costata |
 
Processing with TNRS API @ 'https://tnrsapi.xyz'
Full URL: 'https://tnrsapi.xyz/tnrs_api.php'
 
Name resolution results:
| Name_submitted                        | Name_matched                            | Overall_score | Taxonomic_status | Accepted_name                      | Accepted_name_author      | Source |
| ------------------------------------- | --------------------------------------- | ------------- | ---------------- | ---------------------------------- | ------------------------- | ------ |
| psilochenia occidentalis ssp. costata | Psilochenia occidentalis subsp. costata |          True | Synonym          | Crepis occidentalis subsp. costata | (A.Gray) Babc. & Stebbins | wfo    |

```

**Comment by ojalaquellueva** [comment]
Closing as resolved
