### ISSUE TITLE
TNRS GUI returns names while TNRS function does not

### ISSUE THREAD

**Issue by achmurzy** [EnquistLab/RTNRS#2]
Using 
[names.txt](https://github.com/EnquistLab/RTNRS/files/4636533/names.txt), the GUI on http://tnrs.iplantcollaborative.org/TNRSapp.html
returns the attached list of names [tnrs_results.txt](https://github.com/EnquistLab/RTNRS/files/4636463/tnrs_results.txt)

 under the 'Accepted_name' column, while the TNRS R function does not return most names in the 'Accepted_name' column. Maybe there's a difference in the default settings for the GUI and the R function?

**Comment by achmurzy** [comment]
Here's the exact function call:
names <- read.csv('names.txt')
names <- as.character(unlist(names))
resolved_names <- TNRS(names)

#resolved_names$Accepted_name returns very few names compared to the TNRS GUI

**Comment by bmaitner** [comment]
We seem to have resolved this issue, as this query now returns names for 98.7% of the species in the names.txt file (as opposed to the ~93% in the tnrs_results.txt).
