### ISSUE TITLE
error when run

### ISSUE THREAD

**Issue by cbud** [EnquistLab/RTNRS#4]
When I ran this:

results <- TNRS(taxonomic_names = tnrs_testfile)

I got this:

Error in function (type, msg, asError = TRUE)  : 
  error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

**Comment by bmaitner** [comment]
Thanks for the heads up on this.  I think this might be tied to recent server and database updates.  In the next few days I'll get to work on improving the package so it handles these types of errors in a smarter fashion (i.e. with a more useful error message)

**Comment by bmaitner** [comment]
I've now implemented unit tests that should let us know if the code or the database is down as well as improved error handling that should fail gracefully (and return a more useful message).
