### ISSUE TITLE
Adjust best match algorithm

### ISSUE THREAD

**Issue by paternogbc** [EnquistLab/RTNRS#9]
Hi,

there is any way to allow R users to also adjust the **best match algorithm** in a similar way that is performed in the online https://tnrs.biendata.org/instructions/? I am not sure which was implemented in R (score or higher taxonomy)?

Many thanks!

**Comment by Rekyt** [comment]
Hey Gustavo 👋 
I'm answering because I think I know the answer. From what I'm getting I think it's possible to reproduce the behavior by returning all matches and ranking them by "Highertaxa_score_order" column instead of "Overall_score". If you select the first ones you should get the same answer.

**Comment by paternogbc** [comment]
Hey @Rekyt, thanks. Your solution sounds great!
